### ISSUE TITLE
Types are not working

### ISSUE THREAD

**Issue by PringlePot** [discord-buttons/discord-buttons#113]
The types are not working with discord.js and typescript

**Comment by PringlePot** [comment]
Also urls don't require an emoji, while it is needed in the lib

**Comment by Tolfx** [comment]
> The types are not working with discord.js and typescript

They are currently being worked on in the `dev` branched. And also in #109.

**Comment by PringlePot** [comment]
Issue is not fixed yet. Empheral messages still don't work, and it doesn't even compile

**Comment by xHyroM** [comment]
https://github.com/discord-buttons/discord-buttons/issues/121
