### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: MessageMenuOption is not a constructor

### ISSUE THREAD

**Issue by aravindaan-110** [discord-buttons/discord-buttons#120]
Even after copy pasting the code from examples im getting this error. Please help me out !

**Comment by AngeloCore** [comment]
Update your package to the latest version, you can use `npm i discord-buttons@latest`

**Comment by aravindaan-110** [comment]
How to use the button interaction , im getting lot of errors , can u please post an example

**Comment by xHyroM** [comment]
Check https://discord-buttons.js.org

**Comment by aravindaan-110** [comment]
Can you pleaase tell me how to use it a slappey event ?

**Comment by AngeloCore** [comment]
> Can you pleaase tell me how to use it in a slappey event ?

what?
