### ISSUE TITLE
#113 still not fixed.

### ISSUE THREAD

**Issue by PringlePot** [discord-buttons/discord-buttons#121]
Even after 4.0, issue #113 is still not fixed. The project doesn't even compile when using this as a library.

**Comment by xAtomik** [comment]
Yup, I have the same issue when using dev branch too.

**Comment by MatrixSystemPVP** [comment]
Which exact types are not working?
I am also using TypeScript with the latest dev branch and have no errors.

**Comment by Tolfx** [comment]
@PringlePot @xAtomik 
Mind providing some sort of code, so we can test and resolve the issue. Or make your own `PR` fixing this issue. Unable to help if we don't know how it got arose.
