### ISSUE TITLE
add .setDisabled on messageMenuOption.

### ISSUE THREAD

**Issue by JackCrispy** [discord-buttons/discord-buttons#123]
add the setDisabled option to messagemenuoptions as per docs update on discord api.

**Comment by BliiTzZ** [comment]
Go to the Discord server for feature requests

**Comment by ItsHisoka17** [comment]
I added this method, take a look at [this pull request](https://github.com/discord-buttons/discord-buttons/pull/130)

**Comment by AngeloCore** [comment]
soon
