### ISSUE TITLE
Make discord-slash for handling slash commands

### ISSUE THREAD

**Issue by ririko5834** [discord-buttons/discord-buttons#124]
You should create discord-slash npm package for handling slash commands eaighter using bot's websocket or using express webserver. There should be functions to reply to slash commands too, like this

**Comment by adrifcastr** [comment]
![488828244364230656](https://user-images.githubusercontent.com/22133246/124946283-31d36180-e00f-11eb-9957-9e70ab4d7b46.png)

**Comment by xHyroM** [comment]
> 
> 
> You should create discord-slash npm package for handling slash commands eaighter using bot's websocket or using express webserver. There should be functions to reply to slash commands too, like this

There are very many npm packages that have this and therefore it is quite useless to make another one. 

Example: [discord.js-slash](https://www.npmjs.com/package/discord.js-slash-command) for building and handling
[gcommands](https://www.npmjs.com/package/gcommands) full slash/normal cmds handler

**Comment by BliiTzZ** [comment]
Go to the Discord server for feature requests
