### ISSUE TITLE
button with emoji python

### ISSUE THREAD

**Issue by minecraft76545** [discord-buttons/discord-buttons#128]
Could we explain how to make this button with emoji?

Thank you so much!

<img src="https://i.imgur.com/ff5jgfa.png">

**Comment by GodyFromDiscord** [comment]
**Normal Emoji**

```js
.setEmoji('✅');
```
**But... How to send emoji like that?**
[Here](<https://gblobscdn.gitbook.com/assets%2F-MZ7ByQVRRtOMIeuWMGl%2F-Mb3EnyT3fvMC9rhGwSA%2F-Mb4zUZKu1e7S4meDDc4%2FDiscordDevelopment_kBLYhAzyUT.png>)

**But i want custom emojis!!!**
Get the [emoji ID](<https://gblobscdn.gitbook.com/assets%2F-MZ7ByQVRRtOMIeuWMGl%2F-Mb3EnyT3fvMC9rhGwSA%2F-Mb5-ESne9IhTudW-hP6%2FDiscordDevelopment_uKimBAwB6E.png>)
```js
.setEmoji('535993902180859914');
```

**How to get the emoji id?**
