### ISSUE TITLE
Add multiple lines buttons support

### ISSUE THREAD

**Issue by Nundir** [discord-buttons/discord-buttons#132]
As you can see here : 
 - https://www.reddit.com/r/discordapp/comments/nn733r/tic_tac_toe_using_discords_new_components_aka/
 - https://gist.github.com/giorgi-o/9c7eede3b5c72c8b9f071b6dc8c8cd3c

It is possible to send multiples lines of button, allowing to have more button than the maximum width allowed by Discord and it allow more complex commands.
A support for this would be a good feature.

**Comment by LoneWolf6969** [comment]
The package have this capability couple of version back. You can create a new row utilising ```MessageActionRow()```

**Comment by Nundir** [comment]
Oh, there is a lack of documentation on this feature then or i'm juste stupid and didn't found it.

Do you have an example to do this ? 
I tried multiple thing with MessageActionRow but I did not managed to have multiple lines.
 - Using multiple addComponents on the same MessageActionRow : Every button on the same row
 - Passing 2 MessageActionRow in send() params : only the 2 first button showed
 - Passing a array of MessageActionRow in send() params : Did nothing, zero buttons showed

**Comment by LoneWolf6969** [comment]
> Oh, there is a lack of documentation on this feature then or i'm juste stupid and didn't found it.
> 
> Do you have an example to do this ?
> I tried multiple thing with MessageActionRow but I did not managed to have multiple lines.
> 
> * Using multiple addComponents on the same MessageActionRow : Every button on the same row
> * Passing 2 MessageActionRow in send() params : only the 2 first button showed
> * Passing a array of MessageActionRow in send() params : Did nothing, zero buttons showed

https://discord-buttons.js.org/docs/stable/examples/buttons.html#normal-buttons
You can find everything in this docs

**Comment by Nundir** [comment]
> > Oh, there is a lack of documentation on this feature then or i'm juste stupid and didn't found it.
> > Do you have an example to do this ?
> > I tried multiple thing with MessageActionRow but I did not managed to have multiple lines.
> > 
> > * Using multiple addComponents on the same MessageActionRow : Every button on the same row
> > * Passing 2 MessageActionRow in send() params : only the 2 first button showed
> > * Passing a array of MessageActionRow in send() params : Did nothing, zero buttons showed
> 
> https://discord-buttons.js.org/docs/stable/examples/buttons.html#normal-buttons
> You can find everything in this docs

I have already seen this page, there are 3 examples but none on how to put buttons on multiples lines, the only example with MessageActionRow explains how to make a line, but not multiples

**Comment by LoneWolf6969** [comment]
```js
const row1 = new MessageActionRow ()
.addComponents(row 1 buttons)

const row2 = new MessageActionRow()
.addComponents(row 2 buttons)

message.channel.send("something", { components: [row1, row2])

```
This should shed a light on your doubts

**Comment by Nundir** [comment]
Thanks you 🙏🏻

PS : An example or a line in the doc with this "components" property would be useful for some people i think
