### ISSUE TITLE
Feature Request: Support for D.JS v13

### ISSUE THREAD

**Issue by mafineeek** [discord-buttons/discord-buttons#134]
Hi, i think Support for DJS v13 should be added...

**Comment by RagnarLothbrok-Odin** [comment]
v13 of Discord.js has native button support.

**Comment by mafineeek** [comment]
but modules like Weky still use discord-buttons

**Comment by EhsanFox** [comment]
During the last djs pr that they removed constructors, we are trying to find a way to support v13, if you are interested in that, you are welcomed to make a pr about it.

**Comment by EhsanFox** [comment]
structers* i meant

**Comment by adrifcastr** [comment]
I doubt you meant either of those

**Comment by EhsanFox** [comment]
I meant structures

**Comment by adrifcastr** [comment]
The spelling equals the code quality

**Comment by JackCrispy** [comment]
discord-buttons will not support Discord.js v13, as it is native to the library. @JacProsser

**Comment by callmenasa-3093** [comment]
V13 removed structures, and it also has native support for buttons & other interactions. So, why making support to that?

**Comment by AngeloCore** [comment]
Hi, recently discord.js removed the custom structures.
We can still `Object.defineProperty`, but why?
discord.js now have their own buttons

**Comment by JacProsser** [comment]
well i believe that for most people it would be easier for them! i say this because a lot of v13 people have came and wanted to use the package. so this is why i'd say people want v13 support

**Comment by callmenasa-3093** [comment]
> well i believe that for most people it would be easier for them! i say this because a lot of v13 people have came and wanted to use the package. so this is why i'd say people want v13 support

I mean, it would be just modifying methods name and etc, it would be a waste of time plus discord.js doesn't support third party libraries

**Comment by JacProsser** [comment]
> > well i believe that for most people it would be easier for them! i say this because a lot of v13 people have came and wanted to use the package. so this is why i'd say people want v13 support
> 
> I mean, it would be just modifying methods name and etc, it would be a waste of time plus discord.js doesn't support third party libraries

well in all honesty it doesn't really matter for me because i only manage the documentation of this package so it can go both ways

**Comment by callmenasa-3093** [comment]
> > > well i believe that for most people it would be easier for them! i say this because a lot of v13 people have came and wanted to use the package. so this is why i'd say people want v13 support
> > 
> > I mean, it would be just modifying methods name and etc, it would be a waste of time plus discord.js doesn't support third party libraries
> 
> well in all honesty it doesn't really matter for me because i only manage the documentation of this package so it can go both ways

Though it can be good for these people who work on replit, they will be stuck on V12

**Comment by xHyroM** [comment]
> 
> 
> > > > well i believe that for most people it would be easier for them! i say this because a lot of v13 people have came and wanted to use the package. so this is why i'd say people want v13 support
> > > 
> > > 
> > > I mean, it would be just modifying methods name and etc, it would be a waste of time plus discord.js doesn't support third party libraries
> > 
> > 
> > well in all honesty it doesn't really matter for me because i only manage the documentation of this package so it can go both ways
> 
> Though it can be good for these people who work on replit, they will be stuck on V12

Where did you get that from? It's easy to put nodejs v14 on the replit.

**Comment by AngeloCore** [comment]
Not planning to support discord.js v13 for now, I'm currently very busy with 2 big libraries.
Stay tuned!

**Comment by LightningBolt62** [comment]
> but modules like Weky still use discord-buttons

but modules like Weky don't support v13 yet. 
If they do in a future update, They don't need `discord-buttons` as v13 has native button support.
