### ISSUE TITLE
Unknown interaction

### ISSUE THREAD

**Issue by c-gross** [discord-buttons/discord-buttons#140]
Hi,

I have added discord buttons to my new bot. But I have issues with defer()

```
....
const yesBtn = new MessageButton()
        .setStyle('green')
        .setLabel('Yes')
        .setID("agb-yes");

    const noBtn = new MessageButton()
        .setStyle('red')
        .setLabel('No')
        .setID("agb-no");

    message.author.send("", {
        buttons: [yesBtn, noBtn],
        embed: agbEmbed
    });



client.on('clickButton', async (button) => {
        if(button.id === 'agb-no') {
            try {
                await button.reply.defer();
            } catch (error) {
                console.error(error);
            }

            button.message.edit({
                buttons: noBtn,
                embed: agbEmbed
            })
        }

        if(button.id === 'agb-yes') {
            try {
                await button.reply.defer(); // <<< this throws an error
            } catch (error) {
                console.error(error);
            }

            const linkBtn = new MessageButton()
                .setStyle('url')
                .setURL(`${URL}`)
                .setLabel('Link');

            button.message.edit({
                buttons: linkBtn,
                embed: agbEmbed
            })
        }
    });
```

DiscordAPIError: Unknown interaction
at RequestHandler.execute (...../node_modules/discord.js/src/rest/RequestHandler.js:154:13)
...
  method: 'post',
  path: '/interactions/...../callback',
  code: 10062,

The buttons are still working but I would like to fix the error. Not sure if I did something wrong.

Using discord.js 12.5.3 and discord-buttons 4.0.0

**Comment by EhsanFox** [comment]
your problem is you don't read the docs and FAQs of the docs, and also, what I'm seeing in your code is, you have a lack of knowledge of how events work!

here are some resources that can help u to understand how events work:
https://nodejs.org/api/events.html

**Comment by c-gross** [comment]
Ok thank you. Since I dont write often discord bots, I was following a tutorial for the fancy buttons :D
