### ISSUE TITLE
boolean instanceof Client

### ISSUE THREAD

**Issue by NotSugden** [discord-buttons/discord-buttons#147]
https://github.com/discord-buttons/discord-buttons/blob/80c92d947df2d25595ebeba58186251666971fd9/src/index.js#L19
https://github.com/discord-buttons/discord-buttons/blob/80c92d947df2d25595ebeba58186251666971fd9/src/index.js#L62
https://github.com/discord-buttons/discord-buttons/blob/80c92d947df2d25595ebeba58186251666971fd9/src/v12/Classes/WebhookClient.js#L6 null instanceof MessageEmbed

code quality: 2/10 would not recommend, `npm i discord.js@dev` recommended over this

**Comment by AngeloCore** [comment]
?

**Comment by NotSugden** [comment]
> ?

exactly what it says on the tin. `boolean instanceof Client` :rofl:

**Comment by LoneWolf6969** [comment]
> https://github.com/discord-buttons/discord-buttons/blob/80c92d947df2d25595ebeba58186251666971fd9/src/index.js#L19
> 
> 
> https://github.com/discord-buttons/discord-buttons/blob/80c92d947df2d25595ebeba58186251666971fd9/src/index.js#L62
> 
> 
> https://github.com/discord-buttons/discord-buttons/blob/80c92d947df2d25595ebeba58186251666971fd9/src/v12/Classes/WebhookClient.js#L6
> 
> null instanceof MessageEmbed
> code quality: 2/10 would not recommend, `npm i discord.js@dev` recommended over this

Noone is forcing anyone to use the package!

**Comment by wutv** [comment]
! returns a boolean, which makes !client => false/true => (false/true) instanceof Client

**Comment by NotSugden** [comment]
> ! returns a boolean, which makes !client => false/true => (false/true) instanceof Client

exactly this
