### ISSUE TITLE
Error: Cannot send any empty message

### ISSUE THREAD

**Issue by Crni39** [discord-buttons/discord-buttons#162]
That error happens every time i use discord-buttons and it affect whole bot.

**Comment by rajamoulimallareddy** [comment]
> That error happens every time i use discord-buttons and it affect whole bot.

is it restarting the bot??

**Comment by JarvoDiscord** [comment]
> That error happens every time i use discord-buttons and it affect whole bot.

Well, there should be either an embed or an message included…
`.send('hi', button)`

**Comment by Crni39** [comment]
@rajamoulimallareddy no i get only cannot send empty message

@JarvoDiscord I'm following all by docs

**Comment by JarvoDiscord** [comment]
Hmmm...

Send some code would you.

**Comment by LoneWolf6969** [comment]
The package changes the `.edit` method. If you are editing a message with embed, you cannot do it like `.edit(theEmbed)`, you'll have to edit it as `.edit({embed: theEmbed})`

**Comment by JarvoDiscord** [comment]
> The package changes the `.edit` method. If you are editing a message with embed, you cannot do it like `.edit(theEmbed)`, you'll have to edit it as `.edit({embed: theEmbed})`

That is not true… `message.channel.send(embed).then(msg => msg.edit(newembed)` works…

**Comment by LoneWolf6969** [comment]
> > The package changes the `.edit` method. If you are editing a message with embed, you cannot do it like `.edit(theEmbed)`, you'll have to edit it as `.edit({embed: theEmbed})`
> 
> That is not true… `message.channel.send(embed).then(msg => msg.edit(newembed)` works…

It was my bad! I was running a old version of the package.

**Comment by Crni39** [comment]
I don't have what to send:

```js
const but1 = new MessageButton()
           .setStyle("url")
           .setURL("url.....")


let embed = new Discord.MessageEmbed()
      .setColor("BLURPLE")
      .setDescription("Success....")


message.channel.send({
       component: but1,
       embed: embed
});```

> I have all things defined

**Comment by Crni39** [comment]
Ooos

**Comment by LoneWolf6969** [comment]
```js
const but1 = new MessageButton()
           .setStyle("url")
           .setLabel("some Button")
           .setURL("url.....")


let embed = new Discord.MessageEmbed()
      .setColor("BLURPLE")
      .setDescription("Success....")


message.channel.send({
       button: but1,
       embed: embed
});
```
Try this and see if it still throws the error

**Comment by Crni39** [comment]
Can i use `button: [ b1, b2]` ?

**Comment by LoneWolf6969** [comment]
> Can i use `button: [ b1, b2 ]` ?

`buttons: [btn1, btn2]`

**Comment by Crni39** [comment]
> > Can i use `button: [ b1, b2 ]` ?
> 
> `buttons: [btn1, btn2]`

If multiple then [] is no needed @AngeloCore?

**Comment by JarvoDiscord** [comment]
You need to create a row and then do `{components: row}`

**Comment by AngeloCore** [comment]
See, if you use `button` or `buttons` option, you have to `buttons: b1` for 1 button, and `buttons: [b1, b2]` for multiple.
> Note: `buttons` option add the button(s) to the first row, if you want multiple rows use `MessageActionRow` and `components: row1` or `components: [row1, row2]` for multiple
