### ISSUE TITLE
button.defer is not a function

### ISSUE THREAD

**Issue by Devilbager** [discord-buttons/discord-buttons#175]
`bot.on('clickButton', async (button) => {
    if (button.id === '1')
    {       
            button.defer();
            button.channel.send("page 1");   
    }
});`

returns `TypeError: button.defer is not a function`

**Comment by keirahela** [comment]
isnt that button.reply.defer(); ??

**Comment by Devilbager** [comment]
> isnt that button.reply.defer(); ??

OMG THANK YOU SO MUCH
